<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1285641</bug_id>
          
          <creation_ts>2015-11-26 01:50:00 -0500</creation_ts>
          <short_desc>python-smmap FTBFS on aarch64</short_desc>
          <delta_ts>2016-05-14 22:41:31 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>python-smmap</component>
          <version>24</version>
          <rep_platform>aarch64</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>922257</blocked>
    
    
    <blocked>1285484</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Yaakov Selkowitz">yselkowi</reporter>
          <assigned_to name="Dennis Gilmore">dennis</assigned_to>
          <cc>dennis</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>python-smmap-0.9.0-5.el7</cf_fixed_in>
          <cf_doc_type>Bug Fix</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-05-14 22:41:31</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>8861861</commentid>
    <comment_count>0</comment_count>
    <who name="Yaakov Selkowitz">yselkowi</who>
    <bug_when>2015-11-26 01:50:34 -0500</bug_when>
    <thetext>Attempting to build python-smmap (either the version currently in epel7 or that in rawhide) on RHELSA fails due to:

https://github.com/gitpython-developers/smmap/issues/25

As noted therein, the test in question has been removed upstream:

https://github.com/gitpython-developers/smmap/commit/18e4aea23644ea43657cb2e6846b6aaf78720c27</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>8910188</commentid>
    <comment_count>1</comment_count>
    <who name="Yaakov Selkowitz">yselkowi</who>
    <bug_when>2015-12-10 22:32:54 -0500</bug_when>
    <thetext>This applies to Fedora as well, so it would seem best to fix it in rawhide and merge that into epel7.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9092588</commentid>
    <comment_count>2</comment_count>
    <who name="Jan Kurik">jkurik</who>
    <bug_when>2016-02-24 09:02:05 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 24 development cycle.
Changing version to &apos;24&apos;.

More information and reason for this action is here:
https://fedoraproject.org/wiki/Fedora_Program_Management/HouseKeeping/Fedora24#Rawhide_Rebase</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9275290</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-04-27 23:39:45 -0400</bug_when>
    <thetext>python-smmap-0.9.0-5.el7 has been submitted as an update to Fedora EPEL 7. https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-5060e7e8f1</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9278427</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-04-28 18:23:11 -0400</bug_when>
    <thetext>python-smmap-0.9.0-5.el7 has been pushed to the Fedora EPEL 7 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-5060e7e8f1</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9326866</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-05-14 22:41:29 -0400</bug_when>
    <thetext>python-smmap-0.9.0-5.el7 has been pushed to the Fedora EPEL 7 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>