<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1311747</bug_id>
          
          <creation_ts>2016-02-24 16:15:00 -0500</creation_ts>
          <short_desc>Packages that depend on pulp-selinux do not Require that package</short_desc>
          <delta_ts>2016-03-03 17:03:19 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>pulp</component>
          <version>24</version>
          <rep_platform>All</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>RAWHIDE</resolution>
          
          
          <bug_file_loc>https://pulp.plan.io/issues/1712</bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>medium</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Randy Barlow">rbarlow</reporter>
          <assigned_to name="Randy Barlow">rbarlow</assigned_to>
          <cc>jeremy</cc>
    
    
    <cc>jortel</cc>
    
    
    <cc>pcreech</cc>
    
    
    <cc>rbarlow</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>pulp-2.8.0-0.7.beta.1.fc24, pulp-2.8.0-0.7.beta.1.fc25</cf_fixed_in>
          <cf_doc_type>Bug Fix</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-03-03 17:03:19</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9095587</commentid>
    <comment_count>0</comment_count>
    <who name="Randy Barlow">rbarlow</who>
    <bug_when>2016-02-24 16:15:08 -0500</bug_when>
    <thetext>Description of problem:
There are at least two packages that depend on pulp-selinux to be installed for correct operation: pulp-server and python-pulp-streamer. Neither of these two examples Require pulp-selinux and so if they are installed in Fedora they will not operate correctly until the user installs pulp-selinux.

We need to identify if any of our other packages also need pulp-selinux and then add the appropriate Requires lines to our spec file.

There is an upstream issue about the upstream spec file as well, so pay attention to whatever other dependencies are discovered there:

https://pulp.plan.io/issues/1712</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9119527</commentid>
    <comment_count>1</comment_count>
    <who name="Randy Barlow">rbarlow</who>
    <bug_when>2016-03-03 17:03:19 -0500</bug_when>
    <thetext>f24:     http://koji.fedoraproject.org/koji/taskinfo?taskID=13218423
rawhide: http://koji.fedoraproject.org/koji/taskinfo?taskID=13218370</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>