<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1341631</bug_id>
          
          <creation_ts>2016-06-01 07:39:00 -0400</creation_ts>
          <short_desc>calibre: ebook-edit crashes with &quot;AttributeError: type object &apos;QUrl&apos; has no attribute &apos;None&apos;&quot;</short_desc>
          <delta_ts>2016-06-18 14:43:25 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>calibre</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>high</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Ahmad Samir">ahmadsamir3891</reporter>
          <assigned_to name="Kevin Fenzi">kevin</assigned_to>
          <cc>chkr</cc>
    
    
    <cc>frankly3d</cc>
    
    
    <cc>helio</cc>
    
    
    <cc>kevin</cc>
    
    
    <cc>nushio</cc>
    
    
    <cc>zbyszek</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>calibre-2.58.0-1.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-06-18 14:43:25</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9376807</commentid>
    <comment_count>0</comment_count>
    <who name="Ahmad Samir">ahmadsamir3891</who>
    <bug_when>2016-06-01 07:39:27 -0400</bug_when>
    <thetext>When editing an epub with ebook-edit from caliber-2.56.0 and trying to open any text file, the program shows an error dialogue then crashes with this error:
$ ebook-edit 
calibre 2.56  embedded-python: False is64bit: True
Linux-4.5.5-300.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four Linux (&apos;64bit&apos;, &apos;&apos;)
(&apos;Linux&apos;, &apos;4.5.5-300.fc24.x86_64&apos;, &apos;#1 SMP Thu May 19 13:05:32 UTC 2016&apos;)
Python 2.7.11
Linux: (&apos;Fedora&apos;, &apos;24&apos;, &apos;Twenty Four&apos;)
Traceback (most recent call last):                                                                        
  File &quot;/usr/lib64/calibre/calibre/gui2/tweak_book/preview.py&quot;, line 223, in createRequest                
    url = unicode(request.url().toString(QUrl.None))                                                      
AttributeError: type object &apos;QUrl&apos; has no attribute &apos;None&apos;


The issue has been fixed upstream:
https://github.com/kovidgoyal/calibre/commit/57450e54e68b3ca155f7ac16983632b6bd458bc6</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9386460</commentid>
    <comment_count>1</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-06-03 17:29:34 -0400</bug_when>
    <thetext>calibre-2.58.0-1.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2016-89ded4dc6a</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9387217</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-06-04 14:25:02 -0400</bug_when>
    <thetext>calibre-2.58.0-1.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-89ded4dc6a</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9397932</commentid>
    <comment_count>3</comment_count>
    <who name="Ahmad Samir">ahmadsamir3891</who>
    <bug_when>2016-06-08 08:49:20 -0400</bug_when>
    <thetext>Fixed with latest calibre update.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9430156</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-06-18 14:43:19 -0400</bug_when>
    <thetext>calibre-2.58.0-1.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>