<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1342485</bug_id>
          
          <creation_ts>2016-06-03 07:36:00 -0400</creation_ts>
          <short_desc>PyXB: PyXB requires both Python 2 and Python 3</short_desc>
          <delta_ts>2016-09-09 05:31:22 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>PyXB</component>
          <version>25</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>RAWHIDE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1285816</blocked>
    
    
    <blocked>1340802</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Tomas Orsava">torsava</reporter>
          <assigned_to name="My Karlsson">mk</assigned_to>
          <cc>dkrejci</cc>
    
    
    <cc>extras-orphan</cc>
    
    
    <cc>mk</cc>
    
    
    <cc>mmahut</cc>
    
    
    <cc>msrb</cc>
    
    
    <cc>pviktori</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-09-09 04:26:05</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9384495</commentid>
    <comment_count>0</comment_count>
    <who name="Tomas Orsava">torsava</who>
    <bug_when>2016-06-03 07:36:31 -0400</bug_when>
    <thetext>The PyXB RPM requires both Python 2 and Python 3.

Except in very special circumstances, there is no need for one package
to drag in both Python stacks. Usually, this is a packaging error: for
example, a stray &quot;/usr/bin/python&quot; shebang in a Python 3 package can
introduce a Python 2 dependency.

Please split your package, or remove the stray dependencies.
There is a section on shebangs in the Python RPM Porting Guide [0]
which covers this issue.

It&apos;s ok to do this in Rawhide only, however, it would be greatly
appreciated if you could push it to Fedora 24 as well.


If anything is unclear, or if you need any kind of assistance, you can
ask on IRC (#fedora-python on Freenode), or reply here. We&apos;ll be happy
to help investigating or fixing this issue!


[0] http://python-rpm-porting.readthedocs.io/en/latest/application-modules.html#are-shebangs-dragging-you-down-to-python-2</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9548976</commentid>
    <comment_count>1</comment_count>
    <who name="Jan Kurik">jkurik</who>
    <bug_when>2016-07-26 00:16:34 -0400</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 25 development cycle.
Changing version to &apos;25&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9637196</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Admin XMLRPC Client">fedora-admin-xmlrpc</who>
    <bug_when>2016-08-22 14:34:04 -0400</bug_when>
    <thetext>This package has changed ownership in the Fedora Package Database.  Reassigning to the new owner of this component.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9678775</commentid>
    <comment_count>3</comment_count>
    <who name="Dominika Krejčí">dkrejci</who>
    <bug_when>2016-09-05 04:11:17 -0400</bug_when>
    <thetext>Hi Marcus,
how is it going? Do you need some help?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9693206</commentid>
    <comment_count>4</comment_count>
    <who name="Petr Viktorin">pviktori</who>
    <bug_when>2016-09-09 04:26:05 -0400</bug_when>
    <thetext>This was fixed in [commit a6b24c5]. Thanks Marcus!



[commit a6b24c5]: http://pkgs.fedoraproject.org/cgit/rpms/PyXB.git/commit/PyXB.spec?id=a6b24c501a79b325c9cef3f44fb734ac29aa11ef</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9693445</commentid>
    <comment_count>5</comment_count>
    <who name="My Karlsson">mk</who>
    <bug_when>2016-09-09 05:31:22 -0400</bug_when>
    <thetext>Nice to hear that it works. I&apos;ll lock into fixing it on F24 as well.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>