<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1387831</bug_id>
          
          <creation_ts>2016-10-22 06:08:00 -0400</creation_ts>
          <short_desc>Cannot start existing containers</short_desc>
          <delta_ts>2017-01-16 14:51:40 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>docker</component>
          <version>25</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Reopened</keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1411980</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Lukas Slebodnik">lslebodn</reporter>
          <assigned_to name="Antonio Murdaca">amurdaca</assigned_to>
          <cc>adimania</cc>
    
    
    <cc>admiller</cc>
    
    
    <cc>amurdaca</cc>
    
    
    <cc>bkabrda</cc>
    
    
    <cc>dwalsh</cc>
    
    
    <cc>ichavero</cc>
    
    
    <cc>jcajka</cc>
    
    
    <cc>jchaloup</cc>
    
    
    <cc>lsm5</cc>
    
    
    <cc>marianne</cc>
    
    
    <cc>miabbott</cc>
    
    
    <cc>miminar</cc>
    
    
    <cc>mpatel</cc>
    
    
    <cc>nalin</cc>
    
    
    <cc>pahan</cc>
    
    
    <cc>riek</cc>
    
    
    <cc>twaugh</cc>
    
    
    <cc>vbatts</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>docker-1.12.6-4.gitf499e8b.fc25</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-01-16 14:51:40</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9812933</commentid>
    <comment_count>0</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-10-22 06:08:56 -0400</bug_when>
    <thetext>Description of problem:
Cannot start existing containers


Version-Release number of selected component (if applicable):
sh$ rpm -qa &quot;docker*&quot;
docker-1.12.2-3.git15c82b8.fc25.x86_64
docker-common-1.12.2-3.git15c82b8.fc25.x86_64

How reproducible:
Deterministic

Steps to Reproduce:
They are not ideal because I cannot reproduce with newly created container
1. sh# docker start 5279c4f1a2ea
Error response from daemon: shim error: docker-runc not installed on system
Error: failed to start containers: 5279c4f1a2ea

Actual results:
Error response from daemon: shim error: docker-runc not installed on system
Error: failed to start containers: 5279c4f1a2ea

Expected results:
no error reported

Additional info:
sh# rpm -ql docker | grep runc
/usr/libexec/docker/docker-runc-current
sh# rpm -ql docker-common | grep runc

and my workaround is:
sh# cd /usr/local/sbin
sh# ln -s /usr/libexec/docker/docker-runc-current docker-runc</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9812939</commentid>
    <comment_count>1</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-10-22 06:15:32 -0400</bug_when>
    <thetext>Debug log from docker-containerd
sh# /usr/libexec/docker/docker-containerd-current --listen unix:///run/containerd.sock --shim /usr/libexec/docker/docker-containerd-shim-current --debug
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=12
DEBU[0000] containerd: supervisor running                cpus=8 memory=15676 runtime=runc runtimeArgs=[] stateDir=/run/containerd
DEBU[0000] containerd: grpc api on /run/containerd.sock



ERRO[0021] containerd: start container                   error=shim error: docker-runc not installed on system id=5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9812955</commentid>
    <comment_count>2</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-10-22 06:19:22 -0400</bug_when>
    <thetext>Debug log from docker.service:
sh# /usr/bin/dockerd-current --add-runtime oci=/usr/libexec/docker/docker-runc-current --default-runtime=oci --containerd /run/containerd.sock --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --selinux-enabled --log-driver=journald -s btrfs --debug  DEBU[0000] Warning: could not change group /var/run/docker.sock to docker: Group docker not found
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
DEBU[0000] libcontainerd: containerd connection state change: CONNECTING
DEBU[0000] libcontainerd: containerd connection state change: READY
DEBU[0000] Using default logging driver journald
DEBU[0000] Golang&apos;s threads limit set to 112680
DEBU[0000] [graphdriver] trying provided driver &quot;btrfs&quot;
DEBU[0000] Using graph driver btrfs
DEBU[0000] Max Concurrent Downloads: 3
DEBU[0000] Max Concurrent Uploads: 5
INFO[0000] Graph migration to content-addressability took 0.00 seconds
DEBU[0000] Loaded container 0449d7df907def40a9e1c563579220132f223acd453e3f0c36afcbee4df4d765

//snip

DEBU[0000] Registering GET, /networks/{id:.*}
DEBU[0000] Registering POST, /networks/create
DEBU[0000] Registering POST, /networks/{id:.*}/connect
DEBU[0000] Registering POST, /networks/{id:.*}/disconnect
DEBU[0000] Registering DELETE, /networks/{id:.*}
INFO[0000] API listen on /var/run/docker.sock





DEBU[0016] Calling POST /v1.24/containers/5279c4f1a2ea/start
INFO[0016] {Action=start, Username=alcik, LoginUID=1000, PID=4446}
DEBU[0016] container mounted via layerStore: /var/lib/docker/btrfs/subvolumes/6467d03ccee5866f531d59276ad439a5417d66339165048fc1ec9dc7276a1c8a
DEBU[0016] Assigning addresses for endpoint broken_container&apos;s interface on network bridge
DEBU[0016] RequestAddress(LocalDefault/172.17.0.0/16, &lt;nil&gt;, map[])
DEBU[0016] Assigning addresses for endpoint broken_container&apos;s interface on network bridge
DEBU[0016] Programming external connectivity on endpoint broken_container (96122d5993ad744e6c84622a108e8920844c4766f7c10ef7e60c603941ddcaa9)
DEBU[0016] createSpec: cgroupsPath: system.slice:docker:5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40
ERRO[0016] Create container failed with error: shim error: docker-runc not installed on system
DEBU[0016] Revoking external connectivity on endpoint broken_container (96122d5993ad744e6c84622a108e8920844c4766f7c10ef7e60c603941ddcaa9)
DEBU[0016] Releasing addresses for endpoint broken_container&apos;s interface on network bridge
DEBU[0016] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)
ERRO[0016] Handler for POST /v1.24/containers/5279c4f1a2ea/start returned error: shim error: docker-runc not installed on system</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9812961</commentid>
    <comment_count>3</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-10-22 06:23:39 -0400</bug_when>
    <thetext>sh# docker inspect 5279c4f1a2ea
[
    {
        &quot;Id&quot;: &quot;5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40&quot;,
        &quot;Created&quot;: &quot;2016-02-26T15:45:24.955957382Z&quot;,
        &quot;Path&quot;: &quot;bash&quot;,
        &quot;Args&quot;: [],
        &quot;State&quot;: {
            &quot;Status&quot;: &quot;exited&quot;,
            &quot;Running&quot;: false,
            &quot;Paused&quot;: false,
            &quot;Restarting&quot;: false,
            &quot;OOMKilled&quot;: false,
            &quot;Dead&quot;: false,
            &quot;Pid&quot;: 0,
            &quot;ExitCode&quot;: 128,
            &quot;Error&quot;: &quot;shim error: docker-runc not installed on system&quot;,
            &quot;StartedAt&quot;: &quot;2016-10-22T09:59:26.447631798Z&quot;,
            &quot;FinishedAt&quot;: &quot;2016-10-22T09:59:28.491022428Z&quot;
        },
        &quot;Image&quot;: &quot;sha256:cbebc878a8f322e110e6b923e0e9752866b805f6d09643d6d0fc0b56d875b813&quot;,
        &quot;ResolvConfPath&quot;: &quot;/var/lib/docker/containers/5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40/resolv.conf&quot;,
        &quot;HostnamePath&quot;: &quot;/var/lib/docker/containers/5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40/hostname&quot;,
        &quot;HostsPath&quot;: &quot;/var/lib/docker/containers/5279c4f1a2eaf153cedaf4f037cc230fd363a9222bded17ecff8e8438a492f40/hosts&quot;,
        &quot;LogPath&quot;: &quot;&quot;,
        &quot;Name&quot;: &quot;/broken_container&quot;,
        &quot;RestartCount&quot;: 0,
        &quot;Driver&quot;: &quot;btrfs&quot;,
        &quot;MountLabel&quot;: &quot;&quot;,
        &quot;ProcessLabel&quot;: &quot;&quot;,
        &quot;AppArmorProfile&quot;: &quot;&quot;,
        &quot;ExecIDs&quot;: null,
        &quot;HostConfig&quot;: {
            &quot;Binds&quot;: [
                &quot;/dev/shm:/sssd_workdir&quot;,
                &quot;/home/user:/home/user&quot;
            ],
            &quot;ContainerIDFile&quot;: &quot;&quot;,
            &quot;LogConfig&quot;: {
                &quot;Type&quot;: &quot;journald&quot;,
                &quot;Config&quot;: {}
            },
            &quot;NetworkMode&quot;: &quot;default&quot;,
            &quot;PortBindings&quot;: {},
            &quot;RestartPolicy&quot;: {
                &quot;Name&quot;: &quot;no&quot;,
                &quot;MaximumRetryCount&quot;: 0
            },
            &quot;AutoRemove&quot;: false,
            &quot;VolumeDriver&quot;: &quot;&quot;,
            &quot;VolumesFrom&quot;: null,
            &quot;CapAdd&quot;: null,
            &quot;CapDrop&quot;: null,
            &quot;Dns&quot;: [],
            &quot;DnsOptions&quot;: [],
            &quot;DnsSearch&quot;: [],
            &quot;ExtraHosts&quot;: null,
            &quot;GroupAdd&quot;: null,
            &quot;IpcMode&quot;: &quot;&quot;,
            &quot;Cgroup&quot;: &quot;&quot;,
            &quot;Links&quot;: null,
            &quot;OomScoreAdj&quot;: 0,
            &quot;PidMode&quot;: &quot;&quot;,
            &quot;Privileged&quot;: true,
            &quot;PublishAllPorts&quot;: false,
            &quot;ReadonlyRootfs&quot;: false,
            &quot;SecurityOpt&quot;: [
                &quot;label:disable&quot;
            ],
            &quot;UTSMode&quot;: &quot;&quot;,
            &quot;UsernsMode&quot;: &quot;&quot;,
            &quot;ShmSize&quot;: 67108864,
            &quot;Runtime&quot;: &quot;runc&quot;,
            &quot;ConsoleSize&quot;: [
                0,
                0
            ],
            &quot;Isolation&quot;: &quot;&quot;,
            &quot;CpuShares&quot;: 0,
            &quot;Memory&quot;: 2147483648,
            &quot;CgroupParent&quot;: &quot;&quot;,
            &quot;BlkioWeight&quot;: 0,
            &quot;BlkioWeightDevice&quot;: null,
            &quot;BlkioDeviceReadBps&quot;: null,
            &quot;BlkioDeviceWriteBps&quot;: null,
            &quot;BlkioDeviceReadIOps&quot;: null,
            &quot;BlkioDeviceWriteIOps&quot;: null,
            &quot;CpuPeriod&quot;: 0,
            &quot;CpuQuota&quot;: 0,
            &quot;CpusetCpus&quot;: &quot;0-4&quot;,
            &quot;CpusetMems&quot;: &quot;&quot;,
            &quot;Devices&quot;: [],
            &quot;DiskQuota&quot;: 0,
            &quot;KernelMemory&quot;: 0,
            &quot;MemoryReservation&quot;: 0,
            &quot;MemorySwap&quot;: 4294967296,
            &quot;MemorySwappiness&quot;: -1,
            &quot;OomKillDisable&quot;: false,
            &quot;PidsLimit&quot;: 0,
            &quot;Ulimits&quot;: null,
            &quot;CpuCount&quot;: 0,
            &quot;CpuPercent&quot;: 0,
            &quot;IOMaximumIOps&quot;: 0,
            &quot;IOMaximumBandwidth&quot;: 0
        },
        &quot;GraphDriver&quot;: {
            &quot;Name&quot;: &quot;btrfs&quot;,
            &quot;Data&quot;: null
        },
        &quot;Mounts&quot;: [
            {
                &quot;Source&quot;: &quot;/home/user&quot;,
                &quot;Destination&quot;: &quot;/home/user&quot;,
                &quot;Mode&quot;: &quot;&quot;,
                &quot;RW&quot;: true,
                &quot;Propagation&quot;: &quot;rprivate&quot;
            },
            {
                &quot;Source&quot;: &quot;/dev/shm&quot;,
                &quot;Destination&quot;: &quot;/sssd_workdir&quot;,
                &quot;Mode&quot;: &quot;&quot;,
                &quot;RW&quot;: true,
                &quot;Propagation&quot;: &quot;rprivate&quot;
            }
        ],
        &quot;Config&quot;: {
            &quot;Hostname&quot;: &quot;5279c4f1a2ea&quot;,
            &quot;Domainname&quot;: &quot;&quot;,
            &quot;User&quot;: &quot;user&quot;,
            &quot;AttachStdin&quot;: true,
            &quot;AttachStdout&quot;: true,
            &quot;AttachStderr&quot;: true,
            &quot;Tty&quot;: true,
            &quot;OpenStdin&quot;: true,
            &quot;StdinOnce&quot;: true,
            &quot;Env&quot;: [
                &quot;PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin&quot;,
                &quot;USER=user&quot;,
                &quot;KRB5CCNAME=KEYRING:persistent:1000:1000&quot;
            ],
            &quot;Cmd&quot;: [
                &quot;bash&quot;
            ],
            &quot;Image&quot;: &quot;lslebodn/beaker&quot;,
            &quot;Volumes&quot;: null,
            &quot;WorkingDir&quot;: &quot;/home/user&quot;,
            &quot;Entrypoint&quot;: null,
            &quot;OnBuild&quot;: null,
            &quot;Labels&quot;: {},
            &quot;StopSignal&quot;: &quot;SIGTERM&quot;
        },
        &quot;NetworkSettings&quot;: {
            &quot;Bridge&quot;: &quot;&quot;,
            &quot;SandboxID&quot;: &quot;a5b75a2313a674c45b16641c236fe78a372d9bf8927ff5df3c1ff04e9ff704a7&quot;,
            &quot;HairpinMode&quot;: false,
            &quot;LinkLocalIPv6Address&quot;: &quot;&quot;,
            &quot;LinkLocalIPv6PrefixLen&quot;: 0,
            &quot;Ports&quot;: null,
            &quot;SandboxKey&quot;: &quot;/var/run/docker/netns/a5b75a2313a6&quot;,
            &quot;SecondaryIPAddresses&quot;: null,
            &quot;SecondaryIPv6Addresses&quot;: null,
            &quot;EndpointID&quot;: &quot;&quot;,
            &quot;Gateway&quot;: &quot;&quot;,
            &quot;GlobalIPv6Address&quot;: &quot;&quot;,
            &quot;GlobalIPv6PrefixLen&quot;: 0,
            &quot;IPAddress&quot;: &quot;&quot;,
            &quot;IPPrefixLen&quot;: 0,
            &quot;IPv6Gateway&quot;: &quot;&quot;,
            &quot;MacAddress&quot;: &quot;&quot;,
            &quot;Networks&quot;: {
                &quot;bridge&quot;: {
                    &quot;IPAMConfig&quot;: null,
                    &quot;Links&quot;: null,
                    &quot;Aliases&quot;: null,
                    &quot;NetworkID&quot;: &quot;7a159955a7e83f6e27cc4c5d456da296bc21d7a79c2491888d6886403c2a57ee&quot;,
                    &quot;EndpointID&quot;: &quot;&quot;,
                    &quot;Gateway&quot;: &quot;&quot;,
                    &quot;IPAddress&quot;: &quot;&quot;,
                    &quot;IPPrefixLen&quot;: 0,
                    &quot;IPv6Gateway&quot;: &quot;&quot;,
                    &quot;GlobalIPv6Address&quot;: &quot;&quot;,
                    &quot;GlobalIPv6PrefixLen&quot;: 0,
                    &quot;MacAddress&quot;: &quot;&quot;
                }
            }
        }
    }
]</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9812966</commentid>
    <comment_count>4</comment_count>
    <who name="Daniel Walsh">dwalsh</who>
    <bug_when>2016-10-22 06:27:09 -0400</bug_when>
    <thetext>Antonio could this be a path issue?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9813148</commentid>
    <comment_count>5</comment_count>
    <who name="Antonio Murdaca">amurdaca</who>
    <bug_when>2016-10-22 10:40:28 -0400</bug_when>
    <thetext>So this is likely a container created with a released version of Docker which had a bug I later fixed (it was a bug in how the Docker service was configured).

Unfortunately I&apos;m not sure we can do anything about this exept telling people to re-create the container (which will then use the correct oci runtime path).

Again, this is an issue with a specific Docker version released some time ago, this version set a wrong runtime path.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9813149</commentid>
    <comment_count>6</comment_count>
    <who name="Antonio Murdaca">amurdaca</who>
    <bug_when>2016-10-22 10:42:02 -0400</bug_when>
    <thetext>Sorry didn&apos;t mean to close it tbh</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9813152</commentid>
    <comment_count>7</comment_count>
    <who name="Antonio Murdaca">amurdaca</who>
    <bug_when>2016-10-22 10:45:32 -0400</bug_when>
    <thetext>But yeah, what I described before is probably what&apos;s happening. Your container is from February 2016 and it has been likely created with a bugged Docker.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9813222</commentid>
    <comment_count>8</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-10-22 13:27:04 -0400</bug_when>
    <thetext>I checked my dnf history and I docker was upgraded to 1:1.10.2-1.git86e59a5.fc23.x86_64 on Wed Feb 24 21:50:56 2016.

And the container was created few days later
&quot;Created&quot;: &quot;2016-02-26T15:45:24.955957382Z&quot;

Can you confirm that I used buggy version of docker?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9826386</commentid>
    <comment_count>9</comment_count>
    <who name="Pavel Alexeev">pahan</who>
    <bug_when>2016-10-27 08:41:27 -0400</bug_when>
    <thetext>I&apos;v got after update:

$ docker start gitlab-runner
Error response from daemon: fork/exec /usr/libexec/docker/docker-containerd-shim: no such file or directory
Error: failed to start containers: gitlab-runner

Container re-creation does not help.

$ sudo dnf history info 1071
…
Transaction ID : 1071
Begin time     : Thu Oct 27 11:45:07 2016
Begin rpmdb    : 4652:421d8fe32fec89cd51f8e8d5ba603e43ccceb52a
End time       :            11:45:48 2016 (41 seconds)
End rpmdb      : 4653:4fb3939aedd9f8df602295b1f5737ee0e5582f20
User           :  &lt;pasha&gt;
Return-Code    : Success
Command Line   : upgrade --refresh
Transaction performed with:
…
    Obsoleting container-selinux-2:1.12.2-3.git15c82b8.fc25.x86_64      @fedora
    Install    container-selinux-2:1.12.2-3.git15c82b8.fc25.x86_64      @fedora
    Upgraded   docker-2:1.12.1-13.git9a3752d.fc25.x86_64                @@commandline
    Upgrade           2:1.12.2-3.git15c82b8.fc25.x86_64                 @fedora
    Install    docker-common-2:1.12.2-3.git15c82b8.fc25.x86_64          @fedora
    Obsoleted  docker-selinux-2:1.12.1-13.git9a3752d.fc25.x86_64        @@commandline
    Upgraded   docker-v1.10-migrator-2:1.12.1-13.git9a3752d.fc25.x86_64 @@commandline
    Upgrade                          2:1.12.2-3.git15c82b8.fc25.x86_64  @fedora</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9876097</commentid>
    <comment_count>10</comment_count>
    <who name="Bohuslav &quot;Slavek&quot; Kabrda">bkabrda</who>
    <bug_when>2016-11-09 09:01:05 -0500</bug_when>
    <thetext>I&apos;m experiencing same problems as Pavel described in comment 9, except I&apos;m trying to create and run a container, not running an existing one.

$ docker run -ti fedora:24 bash
/usr/bin/docker-current: Error response from daemon: fork/exec /usr/libexec/docker/docker-containerd-shim: no such file or directory.

$ rpm -q docker
docker-1.12.3-5.git9a594b9.fc25.x86_64

$ sudo dnf history info
[sudo] password for bkabrda: 
Transaction ID : 608
Begin time     : Wed Nov  9 14:41:05 2016
Begin rpmdb    : 2880:38d14aec1b5b24dbb13521e66060c665bae7ffee
End time       :            14:41:52 2016 (47 seconds)
End rpmdb      : 2882:e86f1267f8a154faf4b3067720c74c11c90bbece
User           : Slavek Kabrda &lt;bkabrda&gt;
Return-Code    : Success
Command Line   : update --enablerepo=updates-testing
Transaction performed with:
    Installed     dnf-1.1.10-3.fc25.noarch @updates-testing
    Installed     rpm-4.13.0-1.fc25.x86_64 @updates-testing
Packages Altered:
    Install    skopeo-containers-0.1.14-5.git550a480.fc25.x86_64   @updates-testing
    Obsoleting container-selinux-2:1.12.3-5.git9a594b9.fc25.x86_64 @updates-testing
    Install    container-selinux-2:1.12.3-5.git9a594b9.fc25.x86_64 @updates-testing
    Upgraded   docker-2:1.12.1-13.git9a3752d.fc25.x86_64           @fedora
    Upgrade           2:1.12.3-5.git9a594b9.fc25.x86_64            @updates-testing
    Install    docker-common-2:1.12.3-5.git9a594b9.fc25.x86_64     @updates-testing
    Obsoleted  docker-selinux-2:1.12.1-13.git9a3752d.fc25.x86_64   @fedora</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9876119</commentid>
    <comment_count>11</comment_count>
    <who name="Bohuslav &quot;Slavek&quot; Kabrda">bkabrda</who>
    <bug_when>2016-11-09 09:09:15 -0500</bug_when>
    <thetext>Ok, I just found out that I had to restart both docker and docker-containerd and everything started working again.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9876124</commentid>
    <comment_count>12</comment_count>
    <who name="Lukas Slebodnik">lslebodn</who>
    <bug_when>2016-11-09 09:10:50 -0500</bug_when>
    <thetext>(In reply to Bohuslav &quot;Slavek&quot; Kabrda from comment #10)
&gt; I&apos;m experiencing same problems as Pavel described in comment 9, except I&apos;m
&gt; trying to create and run a container, not running an existing one.
&gt; 
&gt; $ docker run -ti fedora:24 bash
&gt; /usr/bin/docker-current: Error response from daemon: fork/exec
&gt; /usr/libexec/docker/docker-containerd-shim: no such file or directory.
&gt; 
&gt; $ rpm -q docker
&gt; docker-1.12.3-5.git9a594b9.fc25.x86_64
&gt; 
This BZ is about starting already existing contianer.

You want to start new container.

IIRC you hit other bug with upgrading docker. Following command should help :-)
systemctl restart docker.service docker-containerd.service</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10050655</commentid>
    <comment_count>13</comment_count>
    <who name="Micah Abbott">miabbott</who>
    <bug_when>2017-01-10 15:57:38 -0500</bug_when>
    <thetext>I believe I ran into this issue when I upgraded my RHEL Atomic Host from 7.3.1 to 7.3.2.

On RHELAH 7.3.1, docker 1.10.3-59 was used to create the containers.


I had a private registry created on my system like so:

docker run -d -p 5000:5000 --restart=always --name registry registry:2

After I upgraded to RHELAH 7.3.2 (docker 1.12.5-8), my registry container did not restart as expected:

# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
776b6478ced3        registry:2          &quot;/entrypoint.sh /etc/&quot;   3 minutes ago       Exited (128) 24 seconds ago                       registry


I had to delete the existing container and then run the &apos;docker run&apos; command again to start a fresh container.


# docker rm registry
registry
# docker run -d -p 5000:5000 --restart=always --name registry registry:2
40cc1deb93cd8447b7b3dcc1b31e9a51aba00cf15e5e5d4711525154355e3922
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
40cc1deb93cd        registry:2          &quot;/entrypoint.sh /etc/&quot;   4 seconds ago       Up 2 seconds        0.0.0.0:5000-&gt;5000/tcp   registry


In my experience, it seems like this only affects containers that have exposed ports.  

For example, when I use &apos;atomic run docker.io/cockpit/ws&apos; using docker 1.10 backend, then try to &apos;docker start&apos; the container with docker 1.12, I encounter no problems.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10050657</commentid>
    <comment_count>14</comment_count>
    <who name="Micah Abbott">miabbott</who>
    <bug_when>2017-01-10 15:59:12 -0500</bug_when>
    <thetext>(In reply to Micah Abbott from comment #13)
&gt; I believe I ran into this issue when I upgraded my RHEL Atomic Host from
&gt; 7.3.1 to 7.3.2.
&gt; 
&gt; On RHELAH 7.3.1, docker 1.10.3-59 was used to create the containers.

Oops, I see this was originally opened against Fedora/docker but it looks like the same problem exists on RHEL.  I&apos;ll have to clone this bug for RHEL.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10058590</commentid>
    <comment_count>15</comment_count>
    <who name="Antonio Murdaca">amurdaca</who>
    <bug_when>2017-01-12 14:48:40 -0500</bug_when>
    <thetext>A very basic reproducer for this one just for the record:

- with docker-1.10.x: docker run -d -p 5000:5000 --restart=always --name registry registry:2
- upgrade to docker-1.12.6
- docker ps should show the &quot;registry&quot; container previously started

(without the fix, the last point will fail to show that container as running)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10060493</commentid>
    <comment_count>16</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-13 06:26:32 -0500</bug_when>
    <thetext>docker-1.12.6-4.gitf499e8b.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-4909cf95eb</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10063215</commentid>
    <comment_count>17</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-14 01:21:11 -0500</bug_when>
    <thetext>docker-1.12.6-4.gitf499e8b.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-4909cf95eb</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10067759</commentid>
    <comment_count>18</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-16 14:51:40 -0500</bug_when>
    <thetext>docker-1.12.6-4.gitf499e8b.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>