<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1410896</bug_id>
          
          <creation_ts>2017-01-06 13:14:00 -0500</creation_ts>
          <short_desc>ansible-review doesn&apos;t work, unless I manually install python2-flake8</short_desc>
          <delta_ts>2017-01-25 19:19:14 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>ansible-review</component>
          <version>25</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alan Jenkins">alan.christopher.jenkins</reporter>
          <assigned_to name="Dan Callaghan">dcallagh</assigned_to>
          <cc>dcallagh</cc>
    
    
    <cc>timo</cc>
    
    
    <cc>will</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>ansible-review-0.13.0-2.fc25 ansible-review-0.13.0-2.fc24 ansible-review-0.13.0-2.el7</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-01-12 21:23:50</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10041477</commentid>
    <comment_count>0</comment_count>
    <who name="Alan Jenkins">alan.christopher.jenkins</who>
    <bug_when>2017-01-06 13:14:11 -0500</bug_when>
    <thetext>Description of problem:
ansible-review doesn&apos;t work, unless I manually install python2-flake8.

Version-Release number of selected component (if applicable):
ansible-review-0.13.0-1.fc25.noarch.rpm

$ ansible-review 
Traceback (most recent call last):
  File &quot;/usr/bin/ansible-review&quot;, line 5, in &lt;module&gt;
    from pkg_resources import load_entry_point
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2958, in &lt;module&gt;
    @_call_aside
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2944, in _call_aside
    f(*args, **kwargs)
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2971, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 635, in _build_master
    ws.require(__requires__)
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File &quot;/usr/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The &apos;flake8&apos; distribution was not found and is required by ansible-review</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10047030</commentid>
    <comment_count>1</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-09 16:56:00 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.el7 has been submitted as an update to Fedora EPEL 7. https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-725e09e9a9</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10047037</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-09 16:57:28 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2017-4d52377593</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10047041</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-09 16:58:33 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-09d1d0f7d9</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10047666</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-09 22:24:13 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-4d52377593</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10047732</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-09 22:28:49 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-09d1d0f7d9</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10048529</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-10 05:20:08 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.el7 has been pushed to the Fedora EPEL 7 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-725e09e9a9</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10059380</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-12 21:23:50 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10096820</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-25 15:18:29 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10097334</commentid>
    <comment_count>9</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-01-25 19:19:14 -0500</bug_when>
    <thetext>ansible-review-0.13.0-2.el7 has been pushed to the Fedora EPEL 7 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>