<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1452928</bug_id>
          
          <creation_ts>2017-05-20 09:48:00 -0400</creation_ts>
          <short_desc>SELinux is preventing docker-containe from using the &apos;sigchld&apos; accesses on a process.</short_desc>
          <delta_ts>2017-05-20 11:57:00 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>selinux-policy</component>
          <version>25</version>
          <rep_platform>x86_64</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>CURRENTRELEASE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard>abrt_hash:2f10e814030ee24de556a671fea1ab510798fd904b73cb10855821dd9f37eb8c;</status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Mike Goodwin">mike</reporter>
          <assigned_to name="Lukas Vrabec">lvrabec</assigned_to>
          <cc>dominick.grift</cc>
    
    
    <cc>dwalsh</cc>
    
    
    <cc>lvrabec</cc>
    
    
    <cc>mgrepl</cc>
    
    
    <cc>plautrba</cc>
    
    
    <cc>pmoore</cc>
    
    
    <cc>ssekidde</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-05-20 11:57:00</cf_last_closed>
          <cf_type>---</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10430838</commentid>
    <comment_count>0</comment_count>
    <who name="Mike Goodwin">mike</who>
    <bug_when>2017-05-20 09:48:34 -0400</bug_when>
    <thetext>Description of problem:
Trying to start a docker container (any)
SELinux is preventing docker-containe from using the &apos;sigchld&apos; accesses on a process.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that docker-containe should be allowed sigchld access on processes labeled unconfined_service_t by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c &apos;docker-containe&apos; --raw | audit2allow -M my-dockercontaine
# semodule -X 300 -i my-dockercontaine.pp

Additional Information:
Source Context                system_u:system_r:container_t:s0:c94,c203
Target Context                system_u:system_r:unconfined_service_t:s0
Target Objects                Unknown [ process ]
Source                        docker-containe
Source Path                   docker-containe
Port                          &lt;Unknown&gt;
Host                          (removed)
Source RPM Packages           
Target RPM Packages           
Policy RPM                    selinux-policy-3.13.1-225.16.fc25.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Permissive
Host Name                     (removed)
Platform                      Linux (removed) 4.10.16-200.fc25.x86_64 #1 SMP Mon
                              May 15 15:19:52 UTC 2017 x86_64 x86_64
Alert Count                   5
First Seen                    2017-05-19 17:10:22 EDT
Last Seen                     2017-05-19 19:23:00 EDT
Local ID                      8ed20c80-6159-4da1-ac31-38efca5b8392

Raw Audit Messages
type=AVC msg=audit(1495236180.187:846): avc:  denied  { sigchld } for  pid=15940 comm=&quot;docker-containe&quot; scontext=system_u:system_r:container_t:s0:c94,c203 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process permissive=1


Hash: docker-containe,container_t,unconfined_service_t,process,sigchld

Version-Release number of selected component:
selinux-policy-3.13.1-225.16.fc25.noarch

Additional info:
reporter:       libreport-2.8.0
hashmarkername: setroubleshoot
kernel:         4.10.16-200.fc25.x86_64
type:           libreport</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10430893</commentid>
    <comment_count>1</comment_count>
    <who name="Daniel Walsh">dwalsh</who>
    <bug_when>2017-05-20 11:57:00 -0400</bug_when>
    <thetext>This looks like the docker-containerd process is running with the wrong label.
Please update the container-selinux package out of testing and see if this fixes your issue.

dnf -y update container-selinux  --enable updates-testing

systemctl restart docker</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>