<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1425571</bug_id>
          
          <creation_ts>2017-02-21 13:30:00 -0500</creation_ts>
          <short_desc>python-qtconsole: python2-qtconsole requires both Python 2 and Python 3</short_desc>
          <delta_ts>2017-03-08 08:54:54 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>python-qtconsole</component>
          <version>26</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1285816</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Iryna Shcherbina">ishcherb</reporter>
          <assigned_to name="Mukundan Ragavan">nonamedotc</assigned_to>
          <cc>nonamedotc</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>python-qtconsole-4.2.1-6.fc25</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-03-08 08:54:54</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10172062</commentid>
    <comment_count>0</comment_count>
    <who name="Iryna Shcherbina">ishcherb</who>
    <bug_when>2017-02-21 13:30:39 -0500</bug_when>
    <thetext>The python2-qtconsole RPM requires both Python 2 and Python 3.

Except in very special circumstances, there is no need for one package
to drag in both Python stacks. Usually, this is a packaging error: in this case the Python 2 executable does not override the Python 3 one during installation.

Please remove the stray dependencies.
There is a section on `Moving the Executables and Making Symlinks` in the Python RPM Porting Guide [0] and an example of a ported spec file [1], which covers this issue.


It&apos;s ok to do this in Rawhide only, however, it would be greatly
appreciated if you could push it to Fedora 25 as well.


If anything is unclear, or if you need any kind of assistance, you can
ask on IRC (#fedora-python on Freenode), or reply here. We&apos;ll be happy
to help investigating or fixing this issue!


[0] https://python-rpm-porting.readthedocs.io/en/latest/tools.html#moving-the-executables-and-making-symlinks
[1] https://python-rpm-porting.readthedocs.io/en/latest/tools.html#ported-rpm-spec-file</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10176899</commentid>
    <comment_count>1</comment_count>
    <who name="Mukundan Ragavan">nonamedotc</who>
    <bug_when>2017-02-22 22:02:20 -0500</bug_when>
    <thetext>This should be fixed in rawhide. I will push a F25 update.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10176923</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-22 22:14:20 -0500</bug_when>
    <thetext>python-qtconsole-4.2.1-6.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-232388212d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10180277</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-23 18:21:26 -0500</bug_when>
    <thetext>python-qtconsole-4.2.1-6.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-232388212d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10193398</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora End Of Life">jkurik</who>
    <bug_when>2017-02-28 07:24:21 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 26 development cycle.
Changing version to &apos;26&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10221258</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-08 08:54:54 -0500</bug_when>
    <thetext>python-qtconsole-4.2.1-6.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>